spring:
  application:
    name: gateway
server:
  port: 8080
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
zuul:
  sensitive-headers:
  routes:
    tasks-service:
      path: /tasks-service/**
    uaa:
      path: /uaa/**
security:
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: /uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/authorize
      clientId: client
      clientSecret: secret
    resource:
      userInfoUri: /uaa/users/me
hystrix:
  command:
    tasks-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    uaa:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000