spring:
  application:
    name: tasks-service
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8082
  use-forward-headers: true
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filterOrder: 3
      userInfoUri: /uaa/users/me
management:
  security:
    sessions: never