CREATE TABLE IF NOT EXISTS `tasks` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`TITLE` VARCHAR(500) NOT NULL,
	`COMPLETED` BOOLEAN NOT NULL,
	`CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`START` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`DEADLINE` TIMESTAMP NULL,
	`AUTHOR` VARCHAR(500) NOT NULL,
	PRIMARY KEY (`ID`)
);