CREATE TABLE IF NOT EXISTS `ACCOUNTS` (
	`USERNAME` VARCHAR(500) NOT NULL,
	`PASSWORD` VARCHAR(500) NOT NULL,
	PRIMARY KEY (`USERNAME`)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `USER_ROLE` (
	`USER_NAME` VARCHAR(500) NOT NULL,
	`USER_ROLE` VARCHAR(500) NOT NULL,
	PRIMARY KEY(`USER_NAME`),
	FOREIGN KEY(`USER_NAME`) REFERENCES ACCOUNTS(USERNAME)
) ENGINE=INNODB;